import { createContext, useContext, useEffect, useState } from "react";

type Language = "ku" | "en" | "ar";

type Translations = Record<string, string>;

const dictionary: Record<Language, Translations> = {
  ku: {
    "brand.name": "ڕەشماڵ",
    "nav.marketplace": "بازاڕ",
    "nav.sell": "فرۆشتن",
    "nav.dashboard": "دەستەبژێر",
    "nav.admin": "بەڕێوەبردن",
    "hero.tag": "ڕۆژانە کاڵای نوێ",
    "hero.title": "خوازراو<br/>و ناوازە",
    "hero.subtitle": "کڕین و فرۆشتنی پێڵاوی بەکارهاتوو لە کوردستان",
    "about.title": "دەربارەی ڕەشماڵ",
    "about.body": "ڕەشماڵ شوێنێکی متمانەپێکراوە بۆ کڕین و فرۆشتنی پێڵاوی ناوازە و بەکارهاتووی ڕەسەن لە کوردستان. ئامانجمان بەیەکگەیاندنی کڕیار و فرۆشیارە بە شێوەیەکی ئاسان و پارێزراوە.",
    "about.point1": "ڕەسەنایەتی گەرەنتیکراو",
    "about.point2": "چاتی ڕاستەوخۆ لەگەڵ فرۆشیار",
    "about.point3": "پشتگیری بە هەموو زمانەکانی کوردستان",
    "trending.title": "پڕفرۆشترینەکان",
    "trending.count": "پیشاندانی {count} جووت",
    "trending.empty": "هیچ پێڵاوێک دانەنراوە.",
    "pinned.title": "بەرزکراوەکان",
    "pinned.badge": "پینکراوە",
    "seller.title": "فرۆشتن لە ڕەشماڵ",
    "seller.subtitle": "پێڵاوە ناوازەکانت بخەرە ڕوو بۆ کڕیارانمان.",
    "seller.details": "وردەکارییەکانی بەرهەم",
    "seller.fillOut": "وردەکارییەکانی خوارەوە پڕبکەرەوە بۆ دروستکردنی لیستی بەرهەمەکەت.",
    "seller.nameLabel": "ناوی پێڵاو",
    "seller.namePlaceholder": "نموونە: Jordan 1 Retro High OG",
    "seller.priceLabel": "نرخ (دۆلار)",
    "seller.pricePlaceholder": "0.00",
    "seller.imageLabel": "بەستەری وێنە",
    "seller.imagePlaceholder": "https://example.com/image.jpg",
    "seller.descLabel": "وەسف",
    "seller.descPlaceholder": "باری پێڵاوەکە، بوونی قتیکەی، و تایبەتمەندییەکانی بنووسە...",
    "seller.publishing": "بڵاوکردنەوە...",
    "seller.publish": "بڵاوکردنەوەی بەرهەم",
    "seller.uploadPhoto": "وێنەی پێڵاو باربکە",
    "seller.uploadingPhoto": "باربکردن...",
    "seller.changePhoto": "گۆڕینی وێنە",
    "seller.uploadHint": "PNG, JPG هەتا ١٠ مێگابایت",
    "seller.toastTitle": "بەرهەمەکە زیادکرا",
    "seller.toastDesc": "{name} ئێستا لە بازاڕە.",
    "seller.tabSell": "بەرهەمی نوێ",
    "seller.tabListings": "بەرهەمەکانم",
    "seller.tabOrders": "داواکارییەکان",
    "seller.tabMessages": "نامەکان",
    "seller.myListingsEmpty": "هیچ بەرهەمێکت دانەناوە.",
    "error.name": "ناو دەبێت لانی کەم ٢ پیت بێت",
    "error.price": "نرخ دەبێت زیاتر بێت لە ٠",
    "error.url": "بەستەرێکی دروست بنووسە",
    "error.desc": "وەسف دەبێت لانی کەم ١٠ پیت بێت",
    "error.image": "تکایە وێنەیەکی پێڵاوەکە باربکە",
    "footer.tagline": "بازاڕی پێڵاوی بەکارهاتووی ناوازە. گەرەنتی ڕەسەنایەتی.",
    "404.title": "پەڕەکە نەدۆزرایەوە",
    "404.desc": "ئەو جووتەی بەدوایدا دەگەڕێیت لەوانەیە فرۆشرابێت یان بەستەرەکە شکاوە.",
    "404.back": "گەڕانەوە بۆ بازاڕ",
    "auth.signIn": "چوونە ژوورەوە",
    "auth.signOut": "چوونە دەرەوە",
    "auth.login": "چوونەژوورەوە",
    "auth.signUp": "دروستکردنی هەژمار",
    "auth.email": "ئیمەیڵ",
    "auth.password": "وشەی نهێنی",
    "auth.passwordPlaceholder": "لانی کەم ٦ پیت",
    "auth.name": "ناوی تەواو (ئارەزوومەندانە)",
    "auth.emailPlaceholder": "you@example.com",
    "auth.namePlaceholder": "ناوی تۆ",
    "auth.submit": "بەردەوام بە",
    "auth.submitting": "چاوەڕوانبە...",
    "auth.loginRequired": "پێویستە بچیتە ژوورەوە",
    "auth.loginToBuy": "تکایە بۆ کڕینی ئەم کاڵایە بچۆ ژوورەوە.",
    "auth.loginToSell": "تکایە بۆ دانانی کاڵا بچۆ ژوورەوە.",
    "auth.loginToChat": "تکایە بۆ چاتکردن بچۆ ژوورەوە.",
    "auth.noAccount": "هەژمارت نییە؟",
    "auth.haveAccount": "پێشتر هەژمارت هەیە؟",
    "auth.error.invalidEmail": "تکایە ئیمەیڵێکی دروست بنووسە",
    "auth.error.passwordShort": "وشەی نهێنی دەبێت لانی کەم ٦ پیت بێت",
    "auth.error.emailExists": "ئەم ئیمەیڵە پێشتر تۆمارکراوە",
    "auth.error.invalidCredentials": "ئیمێڵ یان پاسوۆردەکە هەڵەیە",
    "profile.title": "دەستکاریکردنی پرۆفایل",
    "profile.subtitle": "ناو و وێنەی پرۆفایلت نوێبکەرەوە.",
    "profile.save": "پاشەکەوتکردن",
    "profile.edit": "دەستکاری پرۆفایل",
    "location.label": "شوێن",
    "location.erbil": "هەولێر",
    "location.sulaymaniyah": "سلێمانی",
    "location.duhok": "دهۆک",
    "location.kirkuk": "کەرکووک",
    "location.online": "تەنها ئۆنلاین",
    "location.placeholder": "شوێن هەڵبژێرە",
    "checkout.buyNow": "ئێستا بیکڕە",
    "checkout.title": "کڕین",
    "checkout.subtitle": "کڕینەکەت تەواو بکە بۆ {name}",
    "checkout.name": "ناوی تەواو",
    "checkout.phone": "ژمارەی مۆبایل",
    "checkout.address": "ناونیشانی گەیاندن",
    "checkout.submit": "داواکردن",
    "checkout.successTitle": "داواکارییەکەت نێردرا",
    "checkout.successDesc": "داواکارییەکەت بۆ {name} نێردرا بۆ فرۆشیارەکە.",
    "orders.title": "داواکارییەکان",
    "orders.empty": "تا ئێستا هیچ داواکارییەکت نییە.",
    "orders.buyerInfo": "کڕیار: {name}",
    "orders.phone": "مۆبایل: {phone}",
    "orders.address": "ناونیشان: {address}",
    "orders.date": "بەروار: {date}",
    "product.sold": "فرۆشراوە",
    "product.views": "{count} بینەر",
    "product.edit": "دەستکاری",
    "product.delete": "سڕینەوە",
    "product.deleteConfirm": "دڵنیایت لە سڕینەوەی ئەم بەرهەمە؟",
    "product.markSold": "وەک فرۆشراو نیشانبکە",
    "product.markAvailable": "وەک بەردەست نیشانبکە",
    "product.pin": "پینکردن (١٢ کاتژمێر)",
    "product.unpin": "لابردنی پین",
    "product.chatWithSeller": "چات لەگەڵ فرۆشیار",
    "product.save": "پاشەکەوتکردن",
    "product.cancel": "هەڵوەشاندنەوە",
    "product.updated": "بەرهەمەکە نوێکرایەوە",
    "product.deleted": "بەرهەمەکە سڕدرایەوە",
    "chat.title": "چات دەربارەی {name}",
    "chat.placeholder": "نامەیەک بنووسە...",
    "chat.send": "ناردن",
    "chat.empty": "هیچ نامەیەک نییە. یەکەم نامە بنێرە!",
    "messages.title": "نامەکان",
    "messages.empty": "هیچ چاتێکت نییە.",
    "messages.openChat": "کردنەوەی چات",
    "admin.title": "بەڕێوەبردنی گشتی",
    "admin.manageTeam": "بەڕێوەبردنی تیم",
    "admin.manageTeamDesc": "کەسانی نوێ بکە بە ئەدمین یان لابردنی ئەدمین.",
    "admin.emailPlaceholder": "ئیمەیڵی بەکارهێنەر",
    "admin.promote": "کردن بە ئەدمین",
    "admin.demote": "لابردنی ئەدمین",
    "admin.role.user": "بەکارهێنەر",
    "admin.role.admin": "ئەدمین",
    "admin.role.super_admin": "سوپەر ئەدمین",
    "admin.superAdminProtected": "سوپەر ئەدمین ناتوانرێت بگۆڕدرێت.",
    "admin.notAllowed": "تۆ دەسەڵاتی ئەمە نیت.",
    "admin.userList": "لیستی بەکارهێنەران",
    "badge.creator": "دروستکەر 👑",
    "badge.admin": "ئەدمین 🛡️",
    "badge.verified": "١٠٠٪ ئۆرجیناڵ",
    "wishlist.title": "دڵخوازەکانم",
    "wishlist.add": "زیادکردن بۆ دڵخوازەکان",
    "wishlist.remove": "سڕینەوە لە دڵخوازەکان",
    "wishlist.empty": "هیچ شتێکت لە دڵخوازەکان نییە.",
    "share.title": "هاوبەشکردن",
    "share.copied": "بەستەرەکە کۆپیکرا",
    "size.label": "سایز",
    "size.placeholder": "نموونە: 42 EU",
    "condition.label": "پێوەری پاکی (١٠/١٠)",
    "currency.label": "دراو",
    "currency.usd": "دۆلار ($)",
    "currency.iqd": "دیناری عێراقی (د.ع)",
    "gallery.addImage": "زیادکردنی وێنە",
    "gallery.maxImages": "بۆ ٤ وێنە",
  },
  en: {
    "brand.name": "Rashmal",
    "nav.marketplace": "Marketplace",
    "nav.sell": "Sell",
    "nav.dashboard": "Dashboard",
    "nav.admin": "Admin",
    "hero.tag": "New arrivals daily",
    "hero.title": "COVETED<br/>&amp; CURATED",
    "hero.subtitle": "The premier destination for premium used sneakers in Kurdistan.",
    "about.title": "About Rashmal",
    "about.body": "Rashmal is a trusted destination for buying and selling authentic, premium used sneakers across Kurdistan. We bring buyers and sellers together in a simple, secure marketplace.",
    "about.point1": "Guaranteed authenticity",
    "about.point2": "Direct chat with sellers",
    "about.point3": "Support in every Kurdistan language",
    "trending.title": "Trending Now",
    "trending.count": "Showing {count} pairs",
    "trending.empty": "No sneakers listed yet.",
    "pinned.title": "Featured",
    "pinned.badge": "Pinned",
    "seller.title": "Sell on Rashmal",
    "seller.subtitle": "List your premium sneakers to our marketplace of collectors.",
    "seller.details": "Product Details",
    "seller.fillOut": "Fill out the details below to create your listing.",
    "seller.nameLabel": "Sneaker Name",
    "seller.namePlaceholder": "e.g. Jordan 1 Retro High OG",
    "seller.priceLabel": "Price (USD)",
    "seller.pricePlaceholder": "0.00",
    "seller.imageLabel": "Image URL",
    "seller.imagePlaceholder": "https://example.com/image.jpg",
    "seller.descLabel": "Description",
    "seller.descPlaceholder": "Describe the condition, box included, special features...",
    "seller.publishing": "Publishing...",
    "seller.publish": "Publish Listing",
    "seller.uploadPhoto": "Upload sneaker photo",
    "seller.uploadingPhoto": "Uploading...",
    "seller.changePhoto": "Change photo",
    "seller.uploadHint": "PNG or JPG, up to 10MB",
    "seller.toastTitle": "Listing created",
    "seller.toastDesc": "{name} is now live on the marketplace.",
    "seller.tabSell": "New Listing",
    "seller.tabListings": "My Listings",
    "seller.tabOrders": "Orders Received",
    "seller.tabMessages": "Messages",
    "seller.myListingsEmpty": "You haven't listed any sneakers yet.",
    "error.name": "Name must be at least 2 characters",
    "error.price": "Price must be greater than 0",
    "error.url": "Must be a valid URL",
    "error.desc": "Description must be at least 10 characters",
    "error.image": "Please upload a photo of the sneaker",
    "footer.tagline": "Premium Sneaker Resale. Authenticity Guaranteed.",
    "404.title": "Page not found",
    "404.desc": "The pair you're looking for seems to have sold out or the link is broken.",
    "404.back": "Back to Marketplace",
    "auth.signIn": "Sign In",
    "auth.signOut": "Sign Out",
    "auth.login": "Login",
    "auth.signUp": "Sign Up",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "At least 6 characters",
    "auth.name": "Full Name (Optional)",
    "auth.emailPlaceholder": "you@example.com",
    "auth.namePlaceholder": "John Doe",
    "auth.submit": "Continue",
    "auth.submitting": "Please wait...",
    "auth.loginRequired": "Authentication Required",
    "auth.loginToBuy": "Please sign in to purchase this item.",
    "auth.loginToSell": "Please sign in to list an item.",
    "auth.loginToChat": "Please sign in to chat with the seller.",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.error.invalidEmail": "Please enter a valid email address",
    "auth.error.passwordShort": "Password must be at least 6 characters",
    "auth.error.emailExists": "An account with this email already exists",
    "auth.error.invalidCredentials": "Incorrect email or password",
    "profile.title": "Edit Profile",
    "profile.subtitle": "Update your name and profile picture.",
    "profile.save": "Save Changes",
    "profile.edit": "Edit Profile",
    "location.label": "Location",
    "location.erbil": "Erbil",
    "location.sulaymaniyah": "Sulaymaniyah",
    "location.duhok": "Duhok",
    "location.kirkuk": "Kirkuk",
    "location.online": "Online only",
    "location.placeholder": "Select location",
    "checkout.buyNow": "Buy Now",
    "checkout.title": "Checkout",
    "checkout.subtitle": "Complete your purchase for {name}",
    "checkout.name": "Full Name",
    "checkout.phone": "Phone Number",
    "checkout.address": "Delivery Address",
    "checkout.submit": "Place Order",
    "checkout.successTitle": "Order Placed",
    "checkout.successDesc": "Your order for {name} has been sent to the seller.",
    "orders.title": "Orders Received",
    "orders.empty": "You have no orders yet.",
    "orders.buyerInfo": "Buyer: {name}",
    "orders.phone": "Phone: {phone}",
    "orders.address": "Address: {address}",
    "orders.date": "Date: {date}",
    "product.sold": "Sold",
    "product.views": "{count} views",
    "product.edit": "Edit",
    "product.delete": "Delete",
    "product.deleteConfirm": "Are you sure you want to delete this listing?",
    "product.markSold": "Mark as sold",
    "product.markAvailable": "Mark as available",
    "product.pin": "Pin (12 hours)",
    "product.unpin": "Unpin",
    "product.chatWithSeller": "Chat with Seller",
    "product.save": "Save",
    "product.cancel": "Cancel",
    "product.updated": "Listing updated",
    "product.deleted": "Listing deleted",
    "chat.title": "Chat about {name}",
    "chat.placeholder": "Type a message...",
    "chat.send": "Send",
    "chat.empty": "No messages yet. Say hello!",
    "messages.title": "Messages",
    "messages.empty": "You have no conversations yet.",
    "messages.openChat": "Open Chat",
    "admin.title": "Admin Panel",
    "admin.manageTeam": "Manage Team",
    "admin.manageTeamDesc": "Promote users to admin or demote existing admins.",
    "admin.emailPlaceholder": "User email",
    "admin.promote": "Make Admin",
    "admin.demote": "Remove Admin",
    "admin.role.user": "User",
    "admin.role.admin": "Admin",
    "admin.role.super_admin": "Super Admin",
    "admin.superAdminProtected": "The super admin cannot be changed.",
    "admin.notAllowed": "You are not authorized to do this.",
    "admin.userList": "Registered Users",
    "badge.creator": "Creator 👑",
    "badge.admin": "Admin 🛡️",
    "badge.verified": "100% Authentic",
    "wishlist.title": "Wishlist",
    "wishlist.add": "Add to wishlist",
    "wishlist.remove": "Remove from wishlist",
    "wishlist.empty": "You have nothing in your wishlist yet.",
    "share.title": "Share",
    "share.copied": "Link copied",
    "size.label": "Size",
    "size.placeholder": "e.g. 42 EU",
    "condition.label": "Condition Rating (out of 10)",
    "currency.label": "Currency",
    "currency.usd": "US Dollar ($)",
    "currency.iqd": "Iraqi Dinar (IQD)",
    "gallery.addImage": "Add photo",
    "gallery.maxImages": "Up to 4 photos",
  },
  ar: {
    "brand.name": "رشمال",
    "nav.marketplace": "السوق",
    "nav.sell": "بيع",
    "nav.dashboard": "لوحة التحكم",
    "nav.admin": "الإدارة",
    "hero.tag": "وصول جديد يومياً",
    "hero.title": "مرغوب<br/>ومنتقى بعناية",
    "hero.subtitle": "الوجهة الأولى لبيع وشراء الأحذية الرياضية المستعملة الفاخرة في كردستان.",
    "about.title": "عن رشمال",
    "about.body": "رشمال هي وجهة موثوقة لبيع وشراء الأحذية الرياضية الفاخرة المستعملة والأصلية في كردستان. نجمع بين البائعين والمشترين في سوق آمن وسهل الاستخدام.",
    "about.point1": "أصالة مضمونة",
    "about.point2": "محادثة مباشرة مع البائع",
    "about.point3": "دعم بجميع لغات كردستان",
    "trending.title": "رائج الآن",
    "trending.count": "عرض {count} زوج",
    "trending.empty": "لم يتم إدراج أي أحذية رياضية بعد.",
    "pinned.title": "المميزة",
    "pinned.badge": "مثبت",
    "seller.title": "البيع على رشمال",
    "seller.subtitle": "اعرض أحذيتك الرياضية الفاخرة في سوقنا للمشترين.",
    "seller.details": "تفاصيل المنتج",
    "seller.fillOut": "املأ التفاصيل أدناه لإنشاء إدراجك.",
    "seller.nameLabel": "اسم الحذاء الرياضي",
    "seller.namePlaceholder": "مثال: Jordan 1 Retro High OG",
    "seller.priceLabel": "السعر (دولار)",
    "seller.pricePlaceholder": "0.00",
    "seller.imageLabel": "رابط الصورة",
    "seller.imagePlaceholder": "https://example.com/image.jpg",
    "seller.descLabel": "الوصف",
    "seller.descPlaceholder": "صف حالة الحذاء، توفر العلبة، والميزات الخاصة...",
    "seller.publishing": "جاري النشر...",
    "seller.publish": "نشر الإدراج",
    "seller.uploadPhoto": "تحميل صورة الحذاء",
    "seller.uploadingPhoto": "جاري التحميل...",
    "seller.changePhoto": "تغيير الصورة",
    "seller.uploadHint": "PNG أو JPG، حتى 10 ميغابايت",
    "seller.toastTitle": "تم إنشاء الإدراج",
    "seller.toastDesc": "{name} متاح الآن في السوق.",
    "seller.tabSell": "إدراج جديد",
    "seller.tabListings": "إدراجاتي",
    "seller.tabOrders": "الطلبات المستلمة",
    "seller.tabMessages": "الرسائل",
    "seller.myListingsEmpty": "لم تقم بإدراج أي أحذية رياضية بعد.",
    "error.name": "يجب أن يتكون الاسم من حرفين على الأقل",
    "error.price": "يجب أن يكون السعر أكبر من 0",
    "error.url": "يجب أن يكون رابطاً صالحاً",
    "error.desc": "يجب أن يتكون الوصف من 10 أحرف على الأقل",
    "error.image": "يرجى تحميل صورة للحذاء الرياضي",
    "footer.tagline": "سوق الأحذية الرياضية الفاخرة المستعملة. أصالة مضمونة.",
    "404.title": "الصفحة غير موجودة",
    "404.desc": "الزوج الذي تبحث عنه ربما تم بيعه أو أن الرابط معطل.",
    "404.back": "العودة إلى السوق",
    "auth.signIn": "تسجيل الدخول",
    "auth.signOut": "تسجيل الخروج",
    "auth.login": "تسجيل الدخول",
    "auth.signUp": "إنشاء حساب",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.passwordPlaceholder": "6 أحرف على الأقل",
    "auth.name": "الاسم الكامل (اختياري)",
    "auth.emailPlaceholder": "you@example.com",
    "auth.namePlaceholder": "اسمك",
    "auth.submit": "متابعة",
    "auth.submitting": "يرجى الانتظار...",
    "auth.loginRequired": "مطلوب تسجيل الدخول",
    "auth.loginToBuy": "يرجى تسجيل الدخول لشراء هذا العنصر.",
    "auth.loginToSell": "يرجى تسجيل الدخول لإدراج عنصر.",
    "auth.loginToChat": "يرجى تسجيل الدخول للمحادثة مع البائع.",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.haveAccount": "هل لديك حساب من قبل؟",
    "auth.error.invalidEmail": "يرجى إدخال بريد إلكتروني صحيح",
    "auth.error.passwordShort": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
    "auth.error.emailExists": "يوجد حساب مسجل بهذا البريد الإلكتروني من قبل",
    "auth.error.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "profile.title": "تعديل الملف الشخصي",
    "profile.subtitle": "حدّث اسمك وصورتك الشخصية.",
    "profile.save": "حفظ التغييرات",
    "profile.edit": "تعديل الملف الشخصي",
    "location.label": "الموقع",
    "location.erbil": "أربيل",
    "location.sulaymaniyah": "السليمانية",
    "location.duhok": "دهوك",
    "location.kirkuk": "كركوك",
    "location.online": "عبر الإنترنت فقط",
    "location.placeholder": "اختر الموقع",
    "checkout.buyNow": "اشتري الآن",
    "checkout.title": "إتمام الشراء",
    "checkout.subtitle": "أكمل عملية الشراء لـ {name}",
    "checkout.name": "الاسم الكامل",
    "checkout.phone": "رقم الهاتف",
    "checkout.address": "عنوان التوصيل",
    "checkout.submit": "تقديم الطلب",
    "checkout.successTitle": "تم تقديم الطلب",
    "checkout.successDesc": "تم إرسال طلبك لـ {name} إلى البائع.",
    "orders.title": "الطلبات المستلمة",
    "orders.empty": "ليس لديك أي طلبات بعد.",
    "orders.buyerInfo": "المشتري: {name}",
    "orders.phone": "الهاتف: {phone}",
    "orders.address": "العنوان: {address}",
    "orders.date": "التاريخ: {date}",
    "product.sold": "مباع",
    "product.views": "{count} مشاهدة",
    "product.edit": "تعديل",
    "product.delete": "حذف",
    "product.deleteConfirm": "هل أنت متأكد من حذف هذا الإدراج؟",
    "product.markSold": "وضع علامة كمباع",
    "product.markAvailable": "وضع علامة كمتاح",
    "product.pin": "تثبيت (12 ساعة)",
    "product.unpin": "إلغاء التثبيت",
    "product.chatWithSeller": "محادثة مع البائع",
    "product.save": "حفظ",
    "product.cancel": "إلغاء",
    "product.updated": "تم تحديث الإدراج",
    "product.deleted": "تم حذف الإدراج",
    "chat.title": "محادثة حول {name}",
    "chat.placeholder": "اكتب رسالة...",
    "chat.send": "إرسال",
    "chat.empty": "لا توجد رسائل بعد. قل مرحباً!",
    "messages.title": "الرسائل",
    "messages.empty": "ليس لديك أي محادثات بعد.",
    "messages.openChat": "فتح المحادثة",
    "admin.title": "لوحة الإدارة",
    "admin.manageTeam": "إدارة الفريق",
    "admin.manageTeamDesc": "ترقية المستخدمين إلى مسؤول أو إزالة مسؤولين حاليين.",
    "admin.emailPlaceholder": "بريد المستخدم",
    "admin.promote": "تعيين كمسؤول",
    "admin.demote": "إزالة المسؤول",
    "admin.role.user": "مستخدم",
    "admin.role.admin": "مسؤول",
    "admin.role.super_admin": "مسؤول رئيسي",
    "admin.superAdminProtected": "لا يمكن تغيير المسؤول الرئيسي.",
    "admin.notAllowed": "غير مخول لك القيام بهذا.",
    "admin.userList": "المستخدمون المسجلون",
    "badge.creator": "المؤسس 👑",
    "badge.admin": "مسؤول 🛡️",
    "badge.verified": "أصلي 100%",
    "wishlist.title": "المفضلة",
    "wishlist.add": "إضافة إلى المفضلة",
    "wishlist.remove": "إزالة من المفضلة",
    "wishlist.empty": "لا يوجد شيء في مفضلتك بعد.",
    "share.title": "مشاركة",
    "share.copied": "تم نسخ الرابط",
    "size.label": "المقاس",
    "size.placeholder": "مثال: 42 EU",
    "condition.label": "تقييم الحالة (من 10)",
    "currency.label": "العملة",
    "currency.usd": "دولار أمريكي ($)",
    "currency.iqd": "دينار عراقي (د.ع)",
    "gallery.addImage": "إضافة صورة",
    "gallery.maxImages": "حتى 4 صور",
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("hb_store_lang");
    return (saved as Language) || "ku";
  });

  useEffect(() => {
    localStorage.setItem("hb_store_lang", language);
    const dir = language === "en" ? "ltr" : "rtl";
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    if (language === "en") {
      document.documentElement.classList.remove("font-arabic");
    } else {
      document.documentElement.classList.add("font-arabic");
    }
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    let str = dictionary[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, String(v));
      });
    }
    return str;
  };

  const dir = language === "en" ? "ltr" : "rtl";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
